CREATE TABLE IF NOT EXISTS PRODUTO_SKU(
    ID bigserial NOT NULL,
    SKU INT ,
    NAME VARCHAR(255),
    INVENTORY INT
);
--
--CREATE TABLE IF NOT EXISTS SKU_INVENTORY(
--    ID INT PRIMARY KEY,
--    ID_ENDERECO INT
--);
--
--CREATE TABLE IF NOT EXISTS SKU_ENDERECO(
--  ID INT PRIMARY KEY,
--  LOCALITY VARCHAR(255),
--  QUANTITY INT,
--  TYPE VARCHAR(125)
--)
